// Interface translations. Currency orders remain in GBP in every language.
window.KITE_LANGUAGES = {
  "en-GB": {
    "dir": "ltr",
    "strings": {
      "pageTitle": "Go With Kite — Travel lighter. Go further.",
      "pageDescription": "Go With Kite. Travel money, your way. Clear prices, simple steps and help that works for you.",
      "skipLink": "Skip to the travel money quote",
      "demoWebsite": "Demo website",
      "demoBanner": "Example prices only. No payments. Sponsorship is not confirmed.",
      "brandHome": "Go With Kite Travel Money home",
      "travelMoney": "Travel money",
      "menu": "Menu",
      "mainNavigation": "Main menu",
      "buyMoney": "Buy travel money",
      "howItWorks": "How it works",
      "help": "Help",
      "accessTools": "Language and accessibility tools",
      "languageLabel": "Choose a language",
      "textLarger": "Make text bigger",
      "textStandard": "Use the normal text size",
      "contrastOn": "Turn high contrast on",
      "contrastOff": "Turn high contrast off",
      "contrast": "Contrast",
      "getQuote": "Get a quote",
      "serviceLabel": "Go With Kite travel money",
      "quoteLabel": "Get an example price",
      "demo": "Demo",
      "youPay": "You pay",
      "youReceive": "You receive",
      "amountError": "Enter an amount from {min} to {max}.",
      "receiveCurrency": "Choose your currency",
      "exampleRate": "Example rate: {pound} = {rate}",
      "deliveryMethod": "How to get your cash",
      "homeDelivery": "Home delivery",
      "homeDeliveryNote": "Sent to your door",
      "collection": "Collection",
      "collectionNote": "Collect from a branch",
      "delivery": "Delivery",
      "total": "Total",
      "reviewOrder": "Check example order",
      "quoteNote": "Example prices only. You cannot pay on this website.",
      "heroEyebrow": "Travel money, your way",
      "heroFirst": "Travel lighter.",
      "heroSecond": "Go further.",
      "heroIntro": "Clear prices. Simple steps. Help that works for you.",
      "photoAlt": "Three friends on a sunny seaside holiday, including a woman using a wheelchair",
      "chatHeading": "Your travel helper",
      "chatIntro": "Ask about costs or delivery.",
      "chatLabel": "Travel helper messages",
      "chatExampleQuestion": "I’m going to Spain. How do I buy euros?",
      "chatExampleAnswer": "Enter how much you want to spend, then choose EUR for euros.",
      "suggestedQuestions": "Questions you can try",
      "explainCosts": "Explain the costs",
      "helpDelivery": "Help with delivery",
      "chatInputLabel": "Ask the travel helper a question",
      "chatPlaceholder": "Type your message…",
      "sendMessage": "Send message",
      "chatNote": "Demo replies only. No live rates.",
      "humanHelp": "Need more help?",
      "textSupport": "Text support",
      "textSupportNote": "Help by message",
      "bslHelp": "BSL help",
      "bslHelpNote": "British Sign Language",
      "benefitsLabel": "Go With Kite benefits",
      "clearPrices": "Clear prices",
      "clearPricesNote": "See all example costs before you decide.",
      "easyOrdering": "Simple ordering",
      "easyOrderingNote": "Easy steps from quote to review.",
      "supportYourWay": "Support your way",
      "supportYourWayNote": "Text, BSL and chat options.",
      "accessMatters": "Why access matters",
      "inclusionHeading": "Different needs. More choice.",
      "inclusionIntro": "Everyone deserves clear information and useful help when planning a holiday.",
      "hearingValue": "430 million",
      "hearingCaption": "people worldwide need care and support for disabling hearing loss",
      "hearingNote": "WHO estimates how many people need hearing rehabilitation. This is not a count of sign-language users.",
      "hearingSource": "Source: WHO hearing loss facts (2026)",
      "disabilityValue": "1.3 billion",
      "disabilityCaption": "people worldwide live with a significant disability",
      "disabilityNote": "About 1 in 6 people, or 16% of the world’s population.",
      "disabilitySource": "Source: WHO disability facts (2023)",
      "dataNote": "These are world estimates, not customer numbers. Some people are in both groups, so do not add the figures together. Sources checked 10 September 2026.",
      "simpleByDesign": "Simple steps",
      "howIntro": "Try this demo. A future currency partner would handle live prices, payments and delivery.",
      "stepOne": "Choose your cash",
      "stepOneNote": "Enter how much you want to spend and choose a currency.",
      "stepTwo": "Ask for help",
      "stepTwoNote": "Try the demo chat or read about planned text and BSL support.",
      "stepThree": "Check the total",
      "stepThreeNote": "Review the example costs. You cannot pay in this demo.",
      "valuesEyebrow": "What matters to us",
      "valuesHeading": "You’re in control.",
      "independence": "Independence",
      "independenceNote": "You choose what works for you.",
      "clarity": "Clarity",
      "clarityNote": "Plain words and clear prices.",
      "choice": "Choice",
      "choiceNote": "Help that suits how you communicate.",
      "inclusion": "Inclusion",
      "inclusionValueNote": "We aim to build and test with people who have different needs.",
      "tagline": "Travel lighter. Go further.",
      "sponsorAria": "Example Travelex sponsorship. Not confirmed.",
      "sponsoredBy": "Sponsored by",
      "sponsorWarning": "Example only. Sponsorship is not confirmed.",
      "closeOrder": "Close order summary",
      "exampleOrder": "Example order",
      "summaryHeading": "Your example order",
      "method": "Delivery choice",
      "demoOnly": "This is a demo.",
      "noPayment": "You cannot pay or place an order. A future currency partner could provide a secure checkout.",
      "returnQuote": "Back to your quote",
      "closeBsl": "Close BSL information",
      "bslFull": "British Sign Language",
      "bslPlanned": "BSL help is planned",
      "bslBody": "We plan to add short BSL videos about prices, delivery and ordering. This demo has no signed videos or live interpreter.",
      "bslPlaceholder": "Space for a future BSL help video",
      "bslVideo": "BSL video coming later",
      "close": "Close",
      "closeSupport": "Close support information",
      "supportPlanned": "Text support is planned",
      "supportBody": "This demo is not linked to a support team. A future service could offer help by message without a phone call.",
      "noScript": "Turn on JavaScript in your browser to use the quote, language choice and demo chat.",
      "replyCosts": "The quote shows the exchange rate and any delivery cost before you check the total. All prices are examples.",
      "replyDelivery": "Choose home delivery or collection. In this demo, delivery is free from {threshold}. Below that, it costs {fee}.",
      "replyBsl": "Use the BSL button to read about planned signed videos. This demo has no live BSL support.",
      "replyRate": "These are set example rates. A future currency partner would provide live rates.",
      "replyDefault": "I can explain example prices, delivery choices and planned BSL help. Try asking about costs or delivery."
    }
  },
  "es-ES": {
    "dir": "ltr",
    "strings": {
      "pageTitle": "Go With Kite — Viaja ligero. Llega más lejos.",
      "pageDescription": "Go With Kite. Dinero para viajar, a tu manera. Precios claros, pasos sencillos y ayuda a tu medida.",
      "skipLink": "Ir al presupuesto de divisas",
      "demoWebsite": "Sitio de demostración",
      "demoBanner": "Solo precios de ejemplo. Sin pagos. Patrocinio no confirmado.",
      "brandHome": "Inicio de Go With Kite",
      "travelMoney": "Dinero para viajar",
      "menu": "Menú",
      "mainNavigation": "Menú principal",
      "buyMoney": "Comprar divisas",
      "howItWorks": "Cómo funciona",
      "help": "Ayuda",
      "accessTools": "Idioma y opciones de accesibilidad",
      "languageLabel": "Elegir idioma",
      "textLarger": "Aumentar el tamaño del texto",
      "textStandard": "Usar el tamaño de texto normal",
      "contrastOn": "Activar el contraste alto",
      "contrastOff": "Desactivar el contraste alto",
      "contrast": "Contraste",
      "getQuote": "Ver un presupuesto",
      "serviceLabel": "Divisas de Go With Kite",
      "quoteLabel": "Ver un precio de ejemplo",
      "demo": "Demo",
      "youPay": "Pagas",
      "youReceive": "Recibes",
      "amountError": "Introduce un importe entre {min} y {max}.",
      "receiveCurrency": "Elegir la divisa",
      "exampleRate": "Cambio de ejemplo: {pound} = {rate}",
      "deliveryMethod": "Cómo recibir el efectivo",
      "homeDelivery": "Envío a domicilio",
      "homeDeliveryNote": "Enviado a tu puerta",
      "collection": "Recogida",
      "collectionNote": "Recoger en una oficina",
      "delivery": "Envío",
      "total": "Total",
      "reviewOrder": "Revisar pedido de ejemplo",
      "quoteNote": "Solo precios de ejemplo. No puedes pagar en esta web.",
      "heroEyebrow": "Dinero para viajar, a tu manera",
      "heroFirst": "Viaja ligero.",
      "heroSecond": "Llega más lejos.",
      "heroIntro": "Precios claros. Pasos sencillos. Ayuda a tu medida.",
      "photoAlt": "Tres amigos de vacaciones junto al mar, incluida una mujer en silla de ruedas",
      "chatHeading": "Tu ayuda para viajar",
      "chatIntro": "Pregunta por los costes o el envío.",
      "chatLabel": "Mensajes de ayuda para viajar",
      "chatExampleQuestion": "Voy a España. ¿Cómo compro euros?",
      "chatExampleAnswer": "Introduce cuánto quieres gastar y elige EUR para recibir euros.",
      "suggestedQuestions": "Preguntas que puedes probar",
      "explainCosts": "Explicar los costes",
      "helpDelivery": "Ayuda con el envío",
      "chatInputLabel": "Haz una pregunta sobre tu viaje",
      "chatPlaceholder": "Escribe tu mensaje…",
      "sendMessage": "Enviar mensaje",
      "chatNote": "Respuestas de demostración. Sin tipos de cambio en tiempo real.",
      "humanHelp": "¿Necesitas más ayuda?",
      "textSupport": "Ayuda por mensaje",
      "textSupportNote": "Comunícate por escrito",
      "bslHelp": "Ayuda en BSL",
      "bslHelpNote": "Lengua de signos británica",
      "benefitsLabel": "Ventajas de Go With Kite",
      "clearPrices": "Precios claros",
      "clearPricesNote": "Consulta todos los costes de ejemplo antes de decidir.",
      "easyOrdering": "Pedido sencillo",
      "easyOrderingNote": "Pasos fáciles, del presupuesto a la revisión.",
      "supportYourWay": "Ayuda a tu manera",
      "supportYourWayNote": "Opciones de texto, BSL y chat.",
      "accessMatters": "Por qué importa el acceso",
      "inclusionHeading": "Distintas necesidades. Más opciones.",
      "inclusionIntro": "Todo el mundo merece información clara y ayuda útil al planificar unas vacaciones.",
      "hearingValue": "430 millones",
      "hearingCaption": "de personas en el mundo necesitan atención y apoyo por una pérdida de audición discapacitante",
      "hearingNote": "La OMS calcula cuántas personas necesitan rehabilitación auditiva. No es un recuento de quienes usan una lengua de signos.",
      "hearingSource": "Fuente: datos de la OMS sobre pérdida auditiva (2026)",
      "disabilityValue": "1.300 millones",
      "disabilityCaption": "de personas en el mundo viven con una discapacidad importante",
      "disabilityNote": "Aproximadamente 1 de cada 6 personas, o el 16 % de la población mundial.",
      "disabilitySource": "Fuente: datos de la OMS sobre discapacidad (2023)",
      "dataNote": "Son estimaciones mundiales, no cifras de clientes. Algunas personas están en ambos grupos: no sumes las cifras. Fuentes consultadas el 10 de septiembre de 2026.",
      "simpleByDesign": "Pasos sencillos",
      "howIntro": "Prueba esta demo. Un futuro proveedor de divisas se encargaría de los precios reales, los pagos y el envío.",
      "stepOne": "Elige tu efectivo",
      "stepOneNote": "Introduce cuánto quieres gastar y elige una divisa.",
      "stepTwo": "Pide ayuda",
      "stepTwoNote": "Prueba el chat de demostración o consulta los planes de ayuda por texto y BSL.",
      "stepThree": "Comprueba el total",
      "stepThreeNote": "Revisa los costes de ejemplo. No puedes pagar en esta demo.",
      "valuesEyebrow": "Lo que nos importa",
      "valuesHeading": "Tú decides.",
      "independence": "Independencia",
      "independenceNote": "Eliges lo que te va mejor.",
      "clarity": "Claridad",
      "clarityNote": "Palabras sencillas y precios claros.",
      "choice": "Elección",
      "choiceNote": "Ayuda adaptada a tu forma de comunicarte.",
      "inclusion": "Inclusión",
      "inclusionValueNote": "Queremos crear y probar el servicio con personas con distintas necesidades.",
      "tagline": "Viaja ligero. Llega más lejos.",
      "sponsorAria": "Ejemplo de patrocinio de Travelex. No confirmado.",
      "sponsoredBy": "Con el patrocinio de",
      "sponsorWarning": "Solo un ejemplo. Patrocinio no confirmado.",
      "closeOrder": "Cerrar resumen del pedido",
      "exampleOrder": "Pedido de ejemplo",
      "summaryHeading": "Tu pedido de ejemplo",
      "method": "Forma de entrega",
      "demoOnly": "Esto es una demostración.",
      "noPayment": "No puedes pagar ni hacer un pedido. Un futuro proveedor de divisas podría ofrecer un pago seguro.",
      "returnQuote": "Volver al presupuesto",
      "closeBsl": "Cerrar información sobre BSL",
      "bslFull": "Lengua de signos británica",
      "bslPlanned": "La ayuda en BSL está prevista",
      "bslBody": "Tenemos previsto añadir vídeos cortos en BSL sobre precios, envío y pedidos. Esta demo no incluye vídeos en lengua de signos ni un intérprete en directo.",
      "bslPlaceholder": "Espacio para un futuro vídeo de ayuda en BSL",
      "bslVideo": "Vídeo en BSL previsto",
      "close": "Cerrar",
      "closeSupport": "Cerrar información de ayuda",
      "supportPlanned": "La ayuda por texto está prevista",
      "supportBody": "Esta demo no está conectada a un equipo de atención. Un futuro servicio podría ofrecer ayuda por mensaje sin llamadas.",
      "noScript": "Activa JavaScript en tu navegador para usar el presupuesto, elegir el idioma y probar el chat.",
      "replyCosts": "El presupuesto muestra el tipo de cambio y los gastos de envío antes de revisar el total. Todos los precios son ejemplos.",
      "replyDelivery": "Elige envío a domicilio o recogida. En esta demo, el envío es gratis a partir de {threshold}. Por debajo, cuesta {fee}.",
      "replyBsl": "Usa el botón BSL para leer los planes de vídeos en lengua de signos británica. Esta demo no tiene ayuda en BSL en directo.",
      "replyRate": "Estos tipos de cambio son ejemplos fijos. Un futuro proveedor de divisas ofrecería tipos de cambio en tiempo real.",
      "replyDefault": "Puedo explicar los precios de ejemplo, las opciones de envío y la ayuda prevista en BSL. Prueba a preguntar por los costes o el envío."
    }
  },
  "fr-FR": {
    "dir": "ltr",
    "strings": {
      "pageTitle": "Go With Kite — Voyagez léger. Allez plus loin.",
      "pageDescription": "Go With Kite. Vos devises, à votre façon. Des prix clairs, des étapes simples et une aide adaptée.",
      "skipLink": "Aller au devis de change",
      "demoWebsite": "Site de démonstration",
      "demoBanner": "Prix donnés à titre d’exemple. Aucun paiement. Parrainage non confirmé.",
      "brandHome": "Accueil de Go With Kite",
      "travelMoney": "Devises de voyage",
      "menu": "Menu",
      "mainNavigation": "Menu principal",
      "buyMoney": "Acheter des devises",
      "howItWorks": "Comment ça marche",
      "help": "Aide",
      "accessTools": "Langue et options d’accessibilité",
      "languageLabel": "Choisir une langue",
      "textLarger": "Agrandir le texte",
      "textStandard": "Utiliser la taille de texte normale",
      "contrastOn": "Activer le contraste élevé",
      "contrastOff": "Désactiver le contraste élevé",
      "contrast": "Contraste",
      "getQuote": "Voir un devis",
      "serviceLabel": "Devises de Go With Kite",
      "quoteLabel": "Voir un prix d’exemple",
      "demo": "Démo",
      "youPay": "Vous payez",
      "youReceive": "Vous recevez",
      "amountError": "Saisissez un montant entre {min} et {max}.",
      "receiveCurrency": "Choisir une devise",
      "exampleRate": "Taux d’exemple : {pound} = {rate}",
      "deliveryMethod": "Comment recevoir vos espèces",
      "homeDelivery": "Livraison à domicile",
      "homeDeliveryNote": "Livrées chez vous",
      "collection": "Retrait",
      "collectionNote": "À retirer en agence",
      "delivery": "Livraison",
      "total": "Total",
      "reviewOrder": "Vérifier la commande d’exemple",
      "quoteNote": "Prix d’exemple uniquement. Aucun paiement sur ce site.",
      "heroEyebrow": "Vos devises, à votre façon",
      "heroFirst": "Voyagez léger.",
      "heroSecond": "Allez plus loin.",
      "heroIntro": "Des prix clairs. Des étapes simples. Une aide adaptée.",
      "photoAlt": "Trois amis en vacances au bord de la mer, dont une femme en fauteuil roulant",
      "chatHeading": "Votre aide au voyage",
      "chatIntro": "Posez une question sur les frais ou la livraison.",
      "chatLabel": "Messages d’aide au voyage",
      "chatExampleQuestion": "Je vais en Espagne. Comment acheter des euros ?",
      "chatExampleAnswer": "Saisissez la somme que vous souhaitez dépenser, puis choisissez EUR pour les euros.",
      "suggestedQuestions": "Questions à essayer",
      "explainCosts": "Expliquer les frais",
      "helpDelivery": "Aide à la livraison",
      "chatInputLabel": "Posez une question sur votre voyage",
      "chatPlaceholder": "Écrivez votre message…",
      "sendMessage": "Envoyer le message",
      "chatNote": "Réponses de démonstration. Aucun taux en temps réel.",
      "humanHelp": "Besoin de plus d’aide ?",
      "textSupport": "Aide par message",
      "textSupportNote": "Communiquez par écrit",
      "bslHelp": "Aide en BSL",
      "bslHelpNote": "Langue des signes britannique",
      "benefitsLabel": "Avantages de Go With Kite",
      "clearPrices": "Des prix clairs",
      "clearPricesNote": "Consultez tous les frais d’exemple avant de décider.",
      "easyOrdering": "Commande simple",
      "easyOrderingNote": "Des étapes faciles, du devis à la vérification.",
      "supportYourWay": "L’aide à votre façon",
      "supportYourWayNote": "Options par texte, BSL et chat.",
      "accessMatters": "Pourquoi l’accès compte",
      "inclusionHeading": "Des besoins différents. Plus de choix.",
      "inclusionIntro": "Tout le monde mérite des informations claires et une aide utile pour préparer ses vacances.",
      "hearingValue": "430 millions",
      "hearingCaption": "de personnes dans le monde ont besoin de soins et d’aide pour une perte auditive invalidante",
      "hearingNote": "L’OMS estime le nombre de personnes ayant besoin d’une réadaptation auditive. Il ne s’agit pas du nombre d’utilisateurs d’une langue des signes.",
      "hearingSource": "Source : données de l’OMS sur la perte auditive (2026)",
      "disabilityValue": "1,3 milliard",
      "disabilityCaption": "de personnes dans le monde vivent avec un handicap important",
      "disabilityNote": "Environ 1 personne sur 6, soit 16 % de la population mondiale.",
      "disabilitySource": "Source : données de l’OMS sur le handicap (2023)",
      "dataNote": "Il s’agit d’estimations mondiales, pas du nombre de clients. Certaines personnes font partie des deux groupes : n’additionnez pas ces chiffres. Sources consultées le 10 septembre 2026.",
      "simpleByDesign": "Des étapes simples",
      "howIntro": "Essayez cette démo. Un futur partenaire de change gérerait les prix réels, les paiements et la livraison.",
      "stepOne": "Choisissez vos espèces",
      "stepOneNote": "Saisissez la somme à dépenser et choisissez une devise.",
      "stepTwo": "Demandez de l’aide",
      "stepTwoNote": "Essayez le chat de démonstration ou découvrez l’aide par texte et BSL prévue.",
      "stepThree": "Vérifiez le total",
      "stepThreeNote": "Consultez les frais d’exemple. Aucun paiement dans cette démo.",
      "valuesEyebrow": "Ce qui compte pour nous",
      "valuesHeading": "Vous décidez.",
      "independence": "Indépendance",
      "independenceNote": "Vous choisissez ce qui vous convient.",
      "clarity": "Clarté",
      "clarityNote": "Des mots simples et des prix clairs.",
      "choice": "Choix",
      "choiceNote": "Une aide adaptée à votre façon de communiquer.",
      "inclusion": "Inclusion",
      "inclusionValueNote": "Nous souhaitons créer et tester le service avec des personnes aux besoins différents.",
      "tagline": "Voyagez léger. Allez plus loin.",
      "sponsorAria": "Exemple de parrainage par Travelex. Non confirmé.",
      "sponsoredBy": "Avec le parrainage de",
      "sponsorWarning": "Exemple uniquement. Parrainage non confirmé.",
      "closeOrder": "Fermer le récapitulatif",
      "exampleOrder": "Commande d’exemple",
      "summaryHeading": "Votre commande d’exemple",
      "method": "Mode de livraison",
      "demoOnly": "Ceci est une démonstration.",
      "noPayment": "Vous ne pouvez ni payer ni passer commande. Un futur partenaire de change pourrait proposer un paiement sécurisé.",
      "returnQuote": "Revenir au devis",
      "closeBsl": "Fermer les informations BSL",
      "bslFull": "Langue des signes britannique",
      "bslPlanned": "Une aide en BSL est prévue",
      "bslBody": "Nous prévoyons de courtes vidéos en BSL sur les prix, la livraison et les commandes. Cette démo ne comprend ni vidéo signée ni interprète en direct.",
      "bslPlaceholder": "Espace pour une future vidéo d’aide en BSL",
      "bslVideo": "Vidéo en BSL prévue",
      "close": "Fermer",
      "closeSupport": "Fermer les informations d’aide",
      "supportPlanned": "Une aide par texte est prévue",
      "supportBody": "Cette démo n’est pas reliée à une équipe d’assistance. Un futur service pourrait proposer une aide par message sans appel téléphonique.",
      "noScript": "Activez JavaScript dans votre navigateur pour utiliser le devis, choisir la langue et essayer le chat.",
      "replyCosts": "Le devis affiche le taux de change et les frais de livraison avant la vérification du total. Tous les prix sont des exemples.",
      "replyDelivery": "Choisissez la livraison à domicile ou le retrait. Dans cette démo, la livraison est gratuite à partir de {threshold}. En dessous, elle coûte {fee}.",
      "replyBsl": "Utilisez le bouton BSL pour découvrir les vidéos prévues en langue des signes britannique. Cette démo ne propose pas d’aide en BSL en direct.",
      "replyRate": "Ces taux sont des exemples fixes. Un futur partenaire de change fournirait les taux en temps réel.",
      "replyDefault": "Je peux expliquer les prix d’exemple, les choix de livraison et l’aide en BSL prévue. Posez une question sur les frais ou la livraison."
    }
  },
  "he-IL": {
    "dir": "rtl",
    "strings": {
      "pageTitle": "Go With Kite — לטייל בקלות. להגיע רחוק יותר.",
      "pageDescription": "Go With Kite. כסף לחופשה, בדרך שלכם. מחירים ברורים, צעדים פשוטים ועזרה שמתאימה לכם.",
      "skipLink": "מעבר להצעת המחיר למטבע חוץ",
      "demoWebsite": "אתר לדוגמה",
      "demoBanner": "המחירים לדוגמה בלבד. אין אפשרות לשלם. החסות לא אושרה.",
      "brandHome": "דף הבית של Go With Kite",
      "travelMoney": "כסף לחופשה",
      "menu": "תפריט",
      "mainNavigation": "תפריט ראשי",
      "buyMoney": "קניית מטבע חוץ",
      "howItWorks": "איך זה עובד",
      "help": "עזרה",
      "accessTools": "שפה ואפשרויות נגישות",
      "languageLabel": "בחירת שפה",
      "textLarger": "הגדלת הטקסט",
      "textStandard": "חזרה לגודל הטקסט הרגיל",
      "contrastOn": "הפעלת ניגודיות גבוהה",
      "contrastOff": "כיבוי ניגודיות גבוהה",
      "contrast": "ניגודיות",
      "getQuote": "קבלת הצעת מחיר",
      "serviceLabel": "מטבע חוץ עם Go With Kite",
      "quoteLabel": "הצעת מחיר לדוגמה",
      "demo": "הדגמה",
      "youPay": "משלמים",
      "youReceive": "מקבלים",
      "amountError": "יש להזין סכום בין {min} ל־{max}.",
      "receiveCurrency": "בחירת מטבע",
      "exampleRate": "שער לדוגמה: {pound} = {rate}",
      "deliveryMethod": "איך לקבל את המזומן",
      "homeDelivery": "משלוח הביתה",
      "homeDeliveryNote": "עד לדלת הבית",
      "collection": "איסוף עצמי",
      "collectionNote": "איסוף מסניף",
      "delivery": "משלוח",
      "total": "סך הכול",
      "reviewOrder": "בדיקת הזמנה לדוגמה",
      "quoteNote": "המחירים לדוגמה בלבד. אין אפשרות לשלם באתר הזה.",
      "heroEyebrow": "כסף לחופשה, בדרך שלכם",
      "heroFirst": "לטייל בקלות.",
      "heroSecond": "להגיע רחוק יותר.",
      "heroIntro": "מחירים ברורים. צעדים פשוטים. עזרה שמתאימה לכם.",
      "photoAlt": "שלושה חברים בחופשה ליד הים, ובהם אישה המשתמשת בכיסא גלגלים",
      "chatHeading": "עזרה לקראת החופשה",
      "chatIntro": "אפשר לשאול על עלויות או משלוח.",
      "chatLabel": "הודעות עזרה לחופשה",
      "chatExampleQuestion": "אני נוסע לספרד. איך קונים אירו?",
      "chatExampleAnswer": "יש להזין כמה רוצים להוציא ולבחור EUR כדי לקבל אירו.",
      "suggestedQuestions": "שאלות שאפשר לנסות",
      "explainCosts": "הסבר על העלויות",
      "helpDelivery": "עזרה עם המשלוח",
      "chatInputLabel": "כתבו שאלה על החופשה",
      "chatPlaceholder": "כתבו את ההודעה שלכם…",
      "sendMessage": "שליחת הודעה",
      "chatNote": "תשובות לדוגמה בלבד. אין שערים בזמן אמת.",
      "humanHelp": "צריכים עוד עזרה?",
      "textSupport": "תמיכה בהודעות",
      "textSupportNote": "עזרה בכתב",
      "bslHelp": "עזרה ב־BSL",
      "bslHelpNote": "שפת הסימנים הבריטית",
      "benefitsLabel": "היתרונות של Go With Kite",
      "clearPrices": "מחירים ברורים",
      "clearPricesNote": "רואים את כל העלויות לדוגמה לפני שמחליטים.",
      "easyOrdering": "הזמנה פשוטה",
      "easyOrderingNote": "צעדים קלים מהצעת המחיר ועד לבדיקה.",
      "supportYourWay": "עזרה בדרך שלכם",
      "supportYourWayNote": "אפשרויות של הודעות, BSL וצ׳אט.",
      "accessMatters": "למה הנגישות חשובה",
      "inclusionHeading": "צרכים שונים. יותר אפשרויות.",
      "inclusionIntro": "לכולם מגיעים מידע ברור ועזרה שימושית בתכנון החופשה.",
      "hearingValue": "430 מיליון",
      "hearingCaption": "אנשים בעולם זקוקים לטיפול ולתמיכה בשל אובדן שמיעה מגביל",
      "hearingNote": "ארגון הבריאות העולמי מעריך כמה אנשים זקוקים לשיקום שמיעה. זה אינו מספר המשתמשים בשפות סימנים.",
      "hearingSource": "מקור: נתוני ארגון הבריאות העולמי על אובדן שמיעה (2026)",
      "disabilityValue": "1.3 מיליארד",
      "disabilityCaption": "אנשים בעולם חיים עם מוגבלות משמעותית",
      "disabilityNote": "כ־1 מכל 6 אנשים, שהם 16% מאוכלוסיית העולם.",
      "disabilitySource": "מקור: נתוני ארגון הבריאות העולמי על מוגבלות (2023)",
      "dataNote": "אלה הערכות עולמיות, לא מספר הלקוחות שלנו. יש אנשים שנכללים בשתי הקבוצות, ולכן אין לחבר את המספרים. המקורות נבדקו ב־10 בספטמבר 2026.",
      "simpleByDesign": "צעדים פשוטים",
      "howIntro": "אפשר לנסות את ההדגמה. בעתיד, שותף להמרת מטבע יוכל לטפל במחירים בזמן אמת, בתשלומים ובמשלוחים.",
      "stepOne": "בחירת המזומן",
      "stepOneNote": "מזינים כמה רוצים להוציא ובוחרים מטבע.",
      "stepTwo": "בקשת עזרה",
      "stepTwoNote": "אפשר לנסות את הצ׳אט לדוגמה או לקרוא על התמיכה המתוכננת בהודעות וב־BSL.",
      "stepThree": "בדיקת הסכום",
      "stepThreeNote": "בודקים את העלויות לדוגמה. אין אפשרות לשלם בהדגמה הזאת.",
      "valuesEyebrow": "מה חשוב לנו",
      "valuesHeading": "אתם מחליטים.",
      "independence": "עצמאות",
      "independenceNote": "אתם בוחרים מה מתאים לכם.",
      "clarity": "בהירות",
      "clarityNote": "מילים פשוטות ומחירים ברורים.",
      "choice": "בחירה",
      "choiceNote": "עזרה שמתאימה לדרך שבה אתם מתקשרים.",
      "inclusion": "הכלה",
      "inclusionValueNote": "אנחנו שואפים לבנות ולבדוק את השירות עם אנשים בעלי צרכים שונים.",
      "tagline": "לטייל בקלות. להגיע רחוק יותר.",
      "sponsorAria": "דוגמה לחסות של Travelex. החסות לא אושרה.",
      "sponsoredBy": "בחסות",
      "sponsorWarning": "דוגמה בלבד. החסות לא אושרה.",
      "closeOrder": "סגירת סיכום ההזמנה",
      "exampleOrder": "הזמנה לדוגמה",
      "summaryHeading": "ההזמנה שלכם לדוגמה",
      "method": "אופן הקבלה",
      "demoOnly": "זאת הדגמה.",
      "noPayment": "אין אפשרות לשלם או לבצע הזמנה. בעתיד, שותף להמרת מטבע יוכל לספק תשלום מאובטח.",
      "returnQuote": "חזרה להצעת המחיר",
      "closeBsl": "סגירת המידע על BSL",
      "bslFull": "שפת הסימנים הבריטית",
      "bslPlanned": "מתוכננת עזרה ב־BSL",
      "bslBody": "אנחנו מתכננים להוסיף סרטונים קצרים ב־BSL על מחירים, משלוחים והזמנות. בהדגמה הזאת אין סרטונים בשפת סימנים או מתורגמן בשידור חי.",
      "bslPlaceholder": "מקום לסרטון עזרה עתידי ב־BSL",
      "bslVideo": "סרטון ב־BSL יתווסף בהמשך",
      "close": "סגירה",
      "closeSupport": "סגירת המידע על התמיכה",
      "supportPlanned": "מתוכננת תמיכה בהודעות",
      "supportBody": "ההדגמה אינה מחוברת לצוות תמיכה. שירות עתידי יוכל להציע עזרה בהודעות, ללא שיחת טלפון.",
      "noScript": "יש להפעיל JavaScript בדפדפן כדי להשתמש בהצעת המחיר, לבחור שפה ולנסות את הצ׳אט.",
      "replyCosts": "הצעת המחיר מציגה את שער ההמרה ואת עלות המשלוח לפני בדיקת הסכום הכולל. כל המחירים הם דוגמאות.",
      "replyDelivery": "אפשר לבחור משלוח הביתה או איסוף עצמי. בהדגמה הזאת, המשלוח חינם מ־{threshold}. מתחת לסכום הזה הוא עולה {fee}.",
      "replyBsl": "לחצו על כפתור BSL כדי לקרוא על הסרטונים המתוכננים בשפת הסימנים הבריטית. בהדגמה הזאת אין תמיכה ב־BSL בשידור חי.",
      "replyRate": "אלה שערי המרה קבועים לדוגמה. בעתיד, שותף להמרת מטבע יוכל לספק שערים בזמן אמת.",
      "replyDefault": "אפשר לקבל הסבר על מחירים לדוגמה, אפשרויות משלוח ועזרה מתוכננת ב־BSL. נסו לשאול על עלויות או משלוח."
    }
  }
};
